In [1]:
def f(x):
    return x**2

print(f(3))

9


In [2]:
def dfdx(x):
    return 2*x

print(dfdx(3))

6


In [3]:
import numpy as np

x_array = np.array([1, 2, 3])

In [5]:
x_array

array([1, 2, 3])

In [6]:
f(x_array)

array([1, 4, 9])

In [7]:
dfdx(x_array)

array([2, 4, 6])

In [8]:
import math

math.sqrt(18)

4.242640687119285

In [11]:
from sympy import *

sqrt(18)

3*sqrt(2)

In [12]:
x, y = symbols('x y')

expr = 2 * x**2 - x * y

expr

2*x**2 - x*y

In [13]:
expr_manip = x * (expr + x * y + x**3)

expr_manip

x*(x**3 + 2*x**2)

In [14]:
expand(expr_manip)

x**4 + 2*x**3

In [15]:
factor(expr_manip)

x**3*(x + 2)

In [16]:
f_symb = x ** 2

x_array = np.array([1, 2, 3])

f_symb(x_array)

TypeError: 'Pow' object is not callable

In [18]:
from sympy.utilities.lambdify import lambdify

f_symb_numpy = lambdify(x, f_symb, 'numpy')

f_symb_numpy(x_array)

array([1, 4, 9])

In [19]:
diff(x**3, x)

3*x**2

In [20]:
dfdx_composed = diff(exp(-2*x) + 3*sin(3*x), x)

dfdx_composed

9*cos(3*x) - 2*exp(-2*x)

In [24]:
f_symb = x ** 2

dfdx_symb = diff(f_symb, x)

dfdx_symb_numpy = lambdify(x, dfdx_symb, 'numpy')

dfdx_symb_numpy(x_array)

array([2, 4, 6])