**This notebook displays how to find solution of a system of linear equations and how to perform elementary operations to a system of linear equations**

# 1. Solving Linear Systems

## 2 variables

In [1]:
# import numpy
import numpy as np

### System of equations with one solution

$$\begin{cases} 
-x_1+3x_2=7, \\ 3x_1+2x_2=1, \end{cases}\tag{1}$$

In [2]:
# express the linear system of 2 variables as a set of matrices
A = np.array([[-1, 3], [3, 2]], dtype = np.dtype(float))

b = np.array([7, 1], dtype = np.dtype(float))

In [3]:
# print matrix A
print(A)

[[-1.  3.]
 [ 3.  2.]]


In [4]:
# print matrix b
print(b)

[7. 1.]


In [5]:
# check the shape of matrix A
A.shape

(2, 2)

In [6]:
# check the shape of matrix b
b.shape

(2,)

In [7]:
# find solution of system
x = np.linalg.solve(A, b)

print(x)

[-1.  2.]


In [8]:
# find the determinant of thge matrix
d = np.linalg.det(A)

print(d)

-11.000000000000002


**System of equations has non zero determinant and hence will have a single solution**

### System of Linear equations with no solutions

$$\begin{cases} 
-x_1+3x_2=7, \\ 3x_1-9x_2=1, \end{cases}\tag{5}$$

In [9]:
A_2 = np.array([[-1, 3], [3, -9]], dtype = np.dtype(float))

b_2 = np.array([7, 1], dtype = np.dtype(float))

In [10]:
A_2.shape

(2, 2)

In [11]:
b_2.shape

(2,)

In [12]:
x_2 = np.linalg.solve(A_2, b_2)

x_2

LinAlgError: Singular matrix

In [ ]:
d_2 = np.linalg.det(A_2)

d_2

0.0

**since the determinant is zero, there is no solution**

### System of equations with Infinite Number of Solutions

$$\begin{cases} 
-x_1+3x_2=7, \\ 3x_1-9x_2=-21, \end{cases}\tag{6}$$

In [ ]:
A_3 = np.array([[-1, 3], [3, -9]], dtype = np.dtype(float))

b_3 = np.array([7, 21], dtype = np.dtype(float))

In [ ]:
A_3.shape

(2, 2)

In [ ]:
b_3.shape

(2,)

In [ ]:
x_3 = np.linalg.solve(A_3, b_3)

x_3

LinAlgError: Singular matrix

In [ ]:
d_3 = np.linalg.det(A_3)

d_3

0.0

**since determinant is zero, solution doesn't have one solution**

## 3 variables

### One solution

$$\begin{cases} 
4x_1-3x_2+x_3=-10, \\ 2x_1+x_2+3x_3=0, \\ -x_1+2x_2-5x_3=17, \end{cases}\tag{1}$$

In [ ]:
A_4 = np.array([[4, -3, 1], [2, 1, 3], [-1, 2, -5]], dtype = np.dtype(float))

b_4 = np.array([-10, 0, 17], dtype = np.dtype(float))

In [ ]:
A_4.shape

(3, 3)

In [ ]:
b_4.shape

(3,)

In [ ]:
x_4 = np.linalg.solve(A_4, b_4)

x_4

array([ 1.,  4., -2.])

In [ ]:
d_4 = np.linalg.det(A_4)

d_4

-60.000000000000036

**since determinant is non-zero, there is only one solution**

### No solution

$$\begin{cases} 
x_1+x_2+x_3=2, \\ x_2-3x_3=1, \\ 2x_1+x_2+5x_3=0, \end{cases}\tag{2}$$

In [ ]:
A_5 = np.array([[1, 1, 1], [0, 1, -3], [2, 1, 5]], dtype = np.dtype(float))

b_5 = np.array([2, 1, 0], dtype = np.dtype(float))

In [ ]:
A_5.shape

(3, 3)

In [ ]:
b_5.shape

(3,)

In [ ]:
x_5 = np.linalg.solve(A_5, b_5)

x_5

LinAlgError: Singular matrix

In [ ]:
d_5 = np.linalg.det(A_5)

d_5

0.0

**since determinant is zero, there is no single solution of the system of equations**

$$\begin{cases} 
x_1+x_2+x_3=2, \\ x_2-3x_3=1, \\ 2x_1+x_2+5x_3=3. \end{cases}\tag{3}$$

In [ ]:
A_6 = np.array([[1, 1, 1], [0, 1, -3], [2, 1, 5]], dtype = np.dtype(float))

b_6 = np.array([2, 1, 3], dtype = np.dtype(float))

In [ ]:
A_6.shape

(3, 3)

In [ ]:
b_6.shape

(3,)

In [ ]:
x_6 = np.linalg.solve(A_6, b_6)

x_6

LinAlgError: Singular matrix

In [ ]:
d_6 = np.linalg.det(A_6)

d_6

0.0

**since the determinant is zero, there is no single solution for this system of equations**

$$\begin{cases} 
2x_1-x_2+x_3+x_4=6, \\ x_1+2x_2-x_3-x_4=3, \\ -x_1+2x_2+2x_3+2x_4=14, \\ x_1-x_2+2x_3+x_4=8, \end{cases}\tag{1}$$

In [13]:
A_7 = np.array([[2, -1, 1, 1], [1, 2, -1, -1], [-1, 2, 2, 2], [1, -1, 2, 1]], dtype = np.dtype(float))

b_7 = np.array([6, 3, 14, 8], dtype = np.dtype(float))

In [14]:
x_7 = np.linalg.solve(A_7, b_7)

x_7

array([2., 3., 4., 1.])

In [16]:
d_7 = np.linalg.det(A_7)

d_7

-17.0

**since the determinant is non zero, the system of equations has a single solution**

# 2. Elementary functions and Row reductions

In [22]:
# define function to multiply any row by non-zero number
def MultiplyRow(M, row_num, row_num_multiple):
    # make a copy of the matrix
    M_new = M.copy()
    # multiply row by non-zero number and replace itself
    M_new[row_num] = M_new[row_num] * row_num_multiple
    return M_new

# define function to add two rows and exchange one of the original rows with the result of the addition
def AddRows(M, row_num_1, row_num_2, row_num_1_multiple):
    # make a copy of the matrix
    M_new = M.copy()
    # multiply row 1 by number, add it to row number 2 and replace that to row number 2
    M_new[row_num_2] = M_new[row_num_1] * row_num_1_multiple + M_new[row_num_2]
    return M_new

# define function to swap rows
def SwapRows(M, row_num_1, row_num_2):
    # make a copy of the matrix
    M_new = M.copy()
    # swap the rows
    M_new[[row_num_1, row_num_2]] = M_new[[row_num_2, row_num_1]]
    return M_new


In [23]:
# create a test array
A_test = np.array([[1, -2, 3, -4], [-5, 6, -7, 8], [-4, 3, -2, 1], [8, -7, 6, -5]],
                  dtype = np.dtype(float))

In [24]:
# multiply 3rd row by -2
MultiplyRow(A_test, 3, -2)

array([[  1.,  -2.,   3.,  -4.],
       [ -5.,   6.,  -7.,   8.],
       [ -4.,   3.,  -2.,   1.],
       [-16.,  14., -12.,  10.]])

In [25]:
# exchange 3rd row with sum of itself and first row multiplied by 4
AddRows(A_test, 1, 3, 4)

array([[  1.,  -2.,   3.,  -4.],
       [ -5.,   6.,  -7.,   8.],
       [ -4.,   3.,  -2.,   1.],
       [-12.,  17., -22.,  27.]])

In [26]:
# exchange 1st row and 3rd row
SwapRows(A_test, 1, 3)

array([[ 1., -2.,  3., -4.],
       [ 8., -7.,  6., -5.],
       [-4.,  3., -2.,  1.],
       [-5.,  6., -7.,  8.]])

In [47]:
A_7 = np.array([[2, -1, 1, 1], [1, 2, -1, -1], [-1, 2, 2, 2], [1, -1, 2, 1]], dtype = np.dtype(float))

b_7 = np.array([6, 3, 14, 8], dtype = np.dtype(float))

def augmented_to_ref(A, b):
    # stack horizontally matrix A and vector b, which needs to be reshaped as a vector (4, 1)
    A_system = np.hstack((A, b.reshape(4, 1)))

    # swap row 0 and row 1 of matrix
    A_ref = SwapRows(A_system, 0, 1)

    # multiply row 0 by -2 and add it to row 1
    A_ref = AddRows(A_ref, 0, 1, -2)

    # add row 0 to row 2, replacing row 2
    A_ref = AddRows(A_ref, 0, 2, 1)

    # multiply row 0 by -1 and add it to row 3
    A_ref = AddRows(A_ref, 0, 3, -1)

    # add row 2 to row 3, replacing row 3
    A_ref = AddRows(A_ref, 2, 3, 1)

    # swap row 1 and 3
    A_ref = SwapRows(A_ref, 1, 3)

    # add row 2 to row 3, replacing row 3
    A_ref = AddRows(A_ref, 2, 3, 1)

    # multiply row 1 by -4 and add it to row 2
    A_ref = AddRows(A_ref, 1, 2, -4)

    # add row 1 to row 3, replacing row 3
    A_ref = AddRows(A_ref, 1, 3, 1)

    # multiply row 3 by 2 and add it to row 2
    A_ref = AddRows(A_ref, 3, 2, 2)

    # multiply row 2 by -8 and add to row 3
    A_ref = AddRows(A_ref, 2, 3, -8)

    # multiply row 3 by -1/17
    A_ref = MultiplyRow(A_ref, 3, -1/17)

    return A_ref

A_ref = augmented_to_ref(A_7, b_7)

A_ref

array([[ 1.,  2., -1., -1.,  3.],
       [ 0.,  1.,  4.,  3., 22.],
       [ 0.,  0.,  1.,  3.,  7.],
       [-0., -0., -0.,  1.,  1.]])

In [50]:
def ref_to_diagonal(A_ref):
    # multiply row 3 by -3 and add to row 2
    A_diag = AddRows(A_ref, 3, 2, -3)
    
    # multiply row 3 by -3 and add to row 1
    A_diag = AddRows(A_diag, 3, 1, -3)

    # add row 3 to row 0, replacing 0
    A_diag = AddRows(A_diag, 3, 0, 1)

    # multiply row 2 by -4 and add to row 1
    A_diag = AddRows(A_diag, 2, 1, -4)

    # add row 2 to row 0, replacing row 0
    A_diag = AddRows(A_diag, 2, 0, 1)

    # multiply row 1 by -2 and add it to row 0
    A_diag = AddRows(A_diag, 1, 0, -2)

    return A_diag

ref_to_diagonal(A_ref)

array([[ 1.,  0.,  0.,  0.,  2.],
       [ 0.,  1.,  0.,  0.,  3.],
       [ 0.,  0.,  1.,  0.,  4.],
       [-0., -0., -0.,  1.,  1.]])