# 1. Matrix Multiplication

In [1]:
# import numpy
import numpy as np

In [2]:
# dot product
x = [1, -2, -5]
y = [4, 3, -1]

def dot(x, y):
    s = 0
    for xi, yi in zip(x, y):
        s += xi * yi
    return s

dot(x, y)

3

In [3]:
np.dot(x, y)

3

In [4]:
# define the vectors as arrays
x = np.array(x)
y = np.array(y)

In [6]:
i = np.array([1, 0, 0])
j = np.array([0, 1, 0])

np.dot(i, j)

0

In [7]:
A = np.array([[4, 9, 9], [9, 1, 6], [9, 2, 3]], dtype = np.dtype(float))

B = np.array([[2, 2], [5, 7], [4, 4]], dtype = np.dtype(float))

np.matmul(A, B)

array([[ 89., 107.],
       [ 47.,  49.],
       [ 40.,  44.]])

In [8]:
x = np.array([1, -2, -5])
y = np.array([4, 3, -1])

np.matmul(x, y)

3

In [9]:
A - 2

array([[ 2.,  7.,  7.],
       [ 7., -1.,  4.],
       [ 7.,  0.,  1.]])

# 2. Linear Transformation

In [10]:
# define a function for linear transformation
def T(v):
    w = np.zeros((3, 1))
    w[0, 0] = 3 * v[0, 0]
    w[2, 0] = -2 * v[1, 0]

    return w

# sample vector
v = np.array([[3], [5]])

# transform the vector
w = T(v)

In [11]:
v

array([[3],
       [5]])

In [12]:
w

array([[  9.],
       [  0.],
       [-10.]])

In [13]:
u = np.array([[1], [-2]])
v = np.array([[2], [4]])

k = 7

In [14]:
u

array([[ 1],
       [-2]])

In [15]:
v

array([[2],
       [4]])

In [16]:
T(k * v)

array([[ 42.],
       [  0.],
       [-56.]])

In [17]:
k * T(v)

array([[ 42.],
       [  0.],
       [-56.]])

In [18]:
T(u + v)

array([[ 9.],
       [ 0.],
       [-4.]])

In [19]:
T(u) + T(v)

array([[ 9.],
       [ 0.],
       [-4.]])

In [20]:
# define function for matrix multiplication
def L(v):
    A = np.array([[3, 0], [0, 0], [0, -2]])
    w = A @ v

    return w

v = np.array([[3], [5]])
w = L(v)

w 

array([[  9],
       [  0],
       [-10]])

In [21]:
def L(v):
    A = np.array([[3, 0], [0, 0], [0, -2]])
    w = A @ v
    return w

v = np.array([[3], [5]])

w = L(v)

w 

array([[  9],
       [  0],
       [-10]])

# 3. Standard Transformations in a Plane

In [23]:
# function for horizontal scaling (dilation)
def T_hscaling(v):
    A = np.array([[2, 0], [0, 1]])
    w = A @ v
    return w

# function to apply transformation to a set of vectors
def transform_vectors(T, v1, v2):
    V = np.hstack((v1.reshape(2, 1), v2.reshape(2, 1)))
    W = T(V)
    return W

e1 = np.array([[1], [0]])
e2 = np.array([[0], [1]])

transformation_result_hscaling = transform_vectors(T_hscaling, e1, e2)

transformation_result_hscaling

array([[2, 0],
       [0, 1]])

In [24]:
# reflection about y axis
def T_reflection_yaxis(v):
    A = np.array([[-1, 0], [0, 1]])
    w = A @ v
    return w

e1 = np.array([[1], [0]])
e2 = np.array([[0], [1]])

transformation_result_reflection_yaxis = transform_vectors(T_reflection_yaxis, e1, e2)

transformation_result_reflection_yaxis

array([[-1,  0],
       [ 0,  1]])